# Generated by Django 5.0.4 on 2024-04-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
