# Generated by Django 5.0.4 on 2024-04-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0008_userdata_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='phone',
        ),
    ]
