# Generated by Django 5.0.4 on 2024-04-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_userorder_delete_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
