# Generated by Django 5.0.4 on 2024-04-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0011_alter_order_date_alter_userorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='password_reset_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
