# Generated by Django 5.0.4 on 2024-04-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0012_userdata_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='password_reset_timestamp',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='password_reset_token',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='verification_code',
        ),
    ]
